### ISSUE TITLE
bring back fb messenger to the help page for problems

### ISSUE THREAD

**Issue by cvraut** [ACM-UCI/ACM-UCI.github.io#1]
I'm getting pretty blasted w/ acm emails regarding problem help. Would prefer if I got blasted in messenger instead, it supports latex

**Comment by pooyakhosravi** [comment]
I think it would even be better if they ask those questions on discord. What do you think?

**Comment by cvraut** [comment]
yes, anything except for email

**Comment by cvraut** [comment]
I currently have 3 separate 5+ emails long threads

**Comment by pooyakhosravi** [comment]
try to redirect those questions to acm-help desk.
